version: '3.2'

services:
  resurface:
    image: docker.resurface.io/release/pilot
    container_name: rails_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  rails_app:
    image: test-rails:latest
    container_name: rails_resurface
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '80:8000'
    depends_on:
      - postgres
    env_file:
      - .env
